name: ci-frontend-workflow 
on:
  workflow_dispatch: 
  push:
    branches: 
      - main 

# LINT-JOB:
jobs:
  LINT-JOB:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2-alpine3.17]
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4 
      # Reference a branch
      - uses: actions/checkout@main

        with:
          node-version: ${{ matrix.node-version }}
    
    #Restore cache
    
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
          
      # Install the dependencies.
      - run: cd starter/frontend && npm install
      #setup cache
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
           

      # Run the linter.
      - run: cd starter/frontend && npm run lint

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}, completed the LINT-JOB  ."
          
# TEST-JOB: 
  TEST-JOB:   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2-alpine3.17]
    steps:
      # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4 
      # Reference a branch
      - uses: actions/checkout@main

        with:
          node-version: ${{ matrix.node-version }}
    
    #Restore cache
    
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
          
      # Install the dependencies.
      - run: cd starter/frontend && npm install
      #setup cache
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
          
      # Run the tests.
      - run: cd starter/frontend && npm test 

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}, completed the TEST-JOB  ."

# BUILD-JOB: 
  BUILD-JOB:
    runs-on: ubuntu-latest
   needs: 
      - LINT-JOB
      - TEST-JOB
    
    strategy:
      matrix:
        node-version: [18.14.2-alpine3.17]
    steps:
    # Reference a specific commit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      # Reference the major version of a release
      - uses: actions/checkout@v4 
      # Reference a branch
      - uses: actions/checkout@main

        with:
          node-version: ${{ matrix.node-version }}
    
    #Restore cache
    
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
          
      # Install the dependencies.
      - run: cd starter/frontend && npm install
      #setup cache
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: starter/frontend/cache
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/lockfiles') }}
          
      # Run the tests.
      - run: cd starter/frontend && npm test 
      
    # build docker 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to container registry
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com  

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/my-image:${{ github.sha }}